### ISSUE TITLE
rulesDirectory not being correctly passed to tslint

### ISSUE THREAD

**Issue by farley911** [SublimeLinter/SublimeLinter-tslint#12]
I attempted to add codelyzer to my linting following the instructions on their npm however when I add any of the codelyzer custom rules to my rules tslint breaks and stops linting my code.

**Comment by JonnyBGod** [comment]
Getting same problem.

This works:
```
{
  "rulesDirectory": [
    "node_modules/codelyzer"
  ],
  "rules": {...}
}
```

This does not work:
```
{
  "rulesDirectory": [
    "node_modules/codelyzer"
  ],
  "extends": [
    "tslint-eslint-rules",
    "tslint-plugin-prettier",
    "tslint-config-prettier"
  ],
  "rules": {...}
}
```

**Comment by braver** [comment]
Guys, please try again with recent versions of SublimeLinter and this plugin, and post full debug logs if it doesn't work.

**Comment by kaste** [comment]
Closing due to age
