### ISSUE TITLE
Does not work along TypeScript-Sublime-Plugin

### ISSUE THREAD

**Issue by Bogidon** [SublimeLinter/SublimeLinter-tslint#19]
There seems to be some kind of conflict between this package and [Microsoft/TypeScript-Sublime-Plugin](https://github.com/Microsoft/TypeScript-Sublime-Plugin). When the other one is enabled, it appears to take precedence and disables all linting overlays.

|program|version|
|-|-|
| Sublime | 3 build 3126 |
| macOS | 10.12.5 |
| SublimeLinter-Contrib-tslint | 1.2.0 |
| TypeScript-Sublime-Plugin | v2.2.0 |

**Comment by thgreasi** [comment]
👍

**Comment by jrodl3r** [comment]
confirmed 👍

**Comment by braver** [comment]
SublimeLinter 4 changes basically everything, so perhaps it's better now. That MS plugin is a monster though, who knows what works or doesn't with that thing installed. This plugin is lean and simple, so if it's not interoperable I doubt it's a problem on our end and/or something we can do anything about.
