### ISSUE TITLE
"lint_mode": "background" not working

### ISSUE THREAD

**Issue by hellraisercenobit** [SublimeLinter/SublimeLinter-tslint#28]
Only working "on save" not in live mode with sublimeLinter v4

**Comment by will-janz** [comment]
I'm coming across the same issue with `lint_mode` set to `background`, but it behaves similarly to `load_save`. An example reproduction would be a TS file with three lint errors, correct one and the other two are no longer highlighted (the "Lint This View" option in the right click menu greys out as well.) The remaining lint highlights and "Lint This View" entry come back on save.

**Comment by burlesona** [comment]
I'm seeing this too, lint errors display when the file is opened but once you touch one of them they disappear.

**Comment by kaste** [comment]
Currently this linter only does work with saved files. That's how it is written. Does tslint actually work feeding it via stdin?

**Comment by kaste** [comment]
Filed issue https://github.com/SublimeLinter/SublimeLinter/issues/1272

**Comment by hellraisercenobit** [comment]
@burlesona nothing appear when the file is opened too for me.
First time after install only.
After, nothing working anymore.
Just on save.

**Comment by braver** [comment]
> Just on save.

Exactly, only way it's going to work. You can *probably* lint ts on the fly using our tempfile solution, but I haven't seen much typescript that makes sense without importing stuff and that would break.

> Does tslint actually work feeding it via stdin?

Nope: https://github.com/palantir/tslint/issues/1590
