### ISSUE TITLE
Cannot figure out how to use with `TypeScriptReact` files

### ISSUE THREAD

**Issue by ChrisW-B** [SublimeLinter/SublimeLinter-tslint#30]
Sorry to post about a potentially just personal issue, but has anyone had success using sublimelinter-tslint with either the TypeScript or TypeScript Syntax's `TypeScriptReact` file types? Everything works perfectly for `Typescript` file types in both of these packages, but neither seem to trigger sublimelinter-tslint in react files in the debugger.

Here's what I have in my sublimelinter config:
```
"syntax_map": {
    "typescriptreact": "typescript",
  },
```

I can post more if that would be helpful, thanks for your help!

**Comment by braver** [comment]
The syntax map is deprecated. If you want to lint additional syntaxes, you add their scopes to the selector setting for that linter. I can probably add `source.tsx` to the default selector here, but you could also try that for yourself first.

**Comment by ChrisW-B** [comment]
thanks so much, that worked perfectly!
Just in case anyone else ends up here because they were also confused by sublimelinter 4's docs, putting this in your config will work
```
{
  "linters": {
    "tslint": {
      "selector": "source.ts, source.tsx"
    }
}
```

**Comment by braver** [comment]
Good to hear that works. With 1.5.0 of this plugin this is again the default behaviour.

**Comment by DominikHoffendahl** [comment]
This is a general issue which is not exclusively related to tslint. Even with Eslint you have to add those `selectors` when using the eslint TypeScript plugin. Please move or rename this issue to cover the general case of SublimeLinter not linting .tsx files

**Comment by kaste** [comment]
@DominikHoffendahl Iirc eslint correctly (and automatically) works for *.ts* files, not supporting *.tsx* might be an issue/bug over there. FWIW.

**Comment by duduindo** [comment]
My solution in 2023:

```js
{
  "linters": {
    "eslint": { // eslint, not tslint
      "env": {
        "PATH": "/usr/bin/"
      },
      "selector": "source.ts, source.tsx" // Here
    }
}
```

Versions:
- Sublime Text Build 4143
- ESlint v8.31.0
- Node v16.18.1

**Comment by kaste** [comment]
eslint automatically sets the selector *iff* it finds either `tsdx` or `@typescript-eslint/parser`

https://github.com/SublimeLinter/SublimeLinter-eslint/blob/master/linter.py#L38-L39
