### ISSUE TITLE
where do install this "Before this plugin will activate"

### ISSUE THREAD

**Issue by ohabash** [SublimeLinter/SublimeLinter-tslint#31]
somehow i do not see this in the package control ui. so where can i clone this repo or how do I make it available in the install menu (cmd+shift+p) => "install packages"

**Comment by kaste** [comment]
Sorry for taking so long. If it is not in install packages then it is probably already installed. Otherwise PackageControl is down. 

You can clone this right into your Packages folder as well `git clone https://github.com/SublimeLinter/SublimeLinter-tslint.git`
