### ISSUE TITLE
TSLint shows errors only after file save

### ISSUE THREAD

**Issue by it6** [SublimeLinter/SublimeLinter-tslint#35]
Not sure if this is expected behavior, with the latest changes I have to save the file in order to see the errors. Is it possible to error on file changes just like `js` does.

**Comment by kaste** [comment]
Technically, this plugin was saved-file-only three months ago as well. Probably bc it was so slow.

**Comment by braver** [comment]
It has always been saved-file-only. Because pretty slow and because that ensures it's in the project context. If someone wants to experiment with temp files be my guest, but I don't think it'll do well.
