### ISSUE TITLE
Missing comma has no output and gutter

### ISSUE THREAD

**Issue by betorobson** [SublimeLinter/SublimeLinter-tslint#38]
Some sintaxes error are not display with gutter and nothing is display on output.
Missing comma example:
<img width="334" alt="screen shot 2018-11-04 at 8 18 07 pm" src="https://user-images.githubusercontent.com/13212208/47970602-1f8b1380-e06f-11e8-9e39-a90d908b7159.png">

However, missing semicolon is display as a error including a output.
<img width="624" alt="screen shot 2018-11-04 at 8 18 42 pm" src="https://user-images.githubusercontent.com/13212208/47970616-316cb680-e06f-11e8-8ce8-adbed12d87bb.png">

Is it just a setting that I have to figure out?

**Comment by kaste** [comment]
Sorry, I'm a bit confused here ... but ... the first screenshot says "',' expected" and underlines 'err'. Isn't this the expected error? Or does this screenshot come from a different plugin?

**Comment by betorobson** [comment]
the first screenshot shows an error that is not display on output. Also, there is not gutter like the second screenshot which has a red bullet on line 57.
They are same plugin.

**Comment by betorobson** [comment]
I find out whats is happen, the Typescript error list is not firing the sublime linter.
When I open command palette and open "Typescript: Show Error List" I got this.

<img width="627" alt="screen shot 2018-11-05 at 11 59 54 pm" src="https://user-images.githubusercontent.com/13212208/48038298-2f7e2280-e157-11e8-9f62-71ea76307691.png">

There is a way to put this erros on the same Sublime linter output including a gutter?

**Comment by betorobson** [comment]
I just found an issue related to this. 
https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/478

Looks like I will not get any solution for this so far :-(

**Comment by braver** [comment]
The TypeScript package !== SublimeLinter-tslint. They work differently and give different output. To find certain categories of problems in Typescript you need a language service and in general a different approach than plain vanilla TSLint. In any case, you cannot expect the errors from the TypeScript package to match and show up in SublimeLinter's results. What you can do is read up on TSLint configuration and how to make it report more kinds of errors.

**Comment by kaste** [comment]
Hm. Do you have the latest and greatest tslint installed? Can you open View > Console and enable debug mode in the SublimeLinter settings and see what gets logged here.

Also, can you lint this file with the syntax error on the command line. 

The idea here is that your tslint reports hard syntax errors maybe on stderr, but this plugin currently only parses stdout.

**Comment by betorobson** [comment]
Here you go. I hope that even Typescript erros are not reported to SublimeLinter-TsLint I could at least show with a gutter and outline instead of underline.
```
reloading plugin TypeScript.main
2018-11-08 10:26:38,519: 140095199273216: WARNING: TypeScript plugin initialized.
plugins loaded
SublimeLinter: log_handler.py:74      Logging installed; log level INFO
SublimeLinter: sublime_linter.py:50   debug mode: on
SublimeLinter: sublime_linter.py:51   version: 4.8.1
SublimeLinter: sublime_linter.py:252  Delay linting '<untitled 30>' for 0.0s
lang_service_enabled: True
Path of tsserver.js: /home/roberto/.config/sublime-text-3/Packages/TypeScript/tsserver/tsserver.js
Path of tsc.js: /home/roberto/.config/sublime-text-3/Packages/TypeScript/tsserver/tsc.js
Trying to spawn node executable from: /usr/bin/node
ref view not found
SublimeLinter: sublime_linter.py:252  Delay linting 'hero-detail.component.ts' for 0.0s
SublimeLinter: linter.py:889          tslint: checking lint mode 'background' vs lint reason 'on_load'
SublimeLinter: #1 linter.py:906       tslint: linting 'hero-detail.component.ts'
SublimeLinter: #1 linter.py:1263      Running ...

  /home/roberto/Work/betorobson-angular-app  (working dir)
  $ /home/roberto/Work/betorobson-angular-app/node_modules/.bin/tslint --format verbose /home/roberto/Work/betorobson-angular-app/src/app/hero-detail/hero-detail.component.ts

SublimeLinter: #1 linter.py:949       tslint: no output
SublimeLinter: sublime_linter.py:449  Linting 'hero-detail.component.ts' took 1.14s
```

**Comment by kaste** [comment]
Please run this exact command from your Terminal

```
  /home/roberto/Work/betorobson-angular-app  (working dir)
  $ /home/roberto/Work/betorobson-angular-app/node_modules/.bin/tslint --format verbose /home/roberto/Work/betorobson-angular-app/src/app/hero-detail/hero-detail.component.ts

```

**Comment by betorobson** [comment]
He you go :-)
```
Warning: The 'deprecation' rule requires type information.
Warning: The 'no-use-before-declare' rule requires type information.
```

**Comment by kaste** [comment]
Is this the latest tslint? Bc if it doesn't report parser errors in the Terminal, please ask in their repo. (Erm, if you used this in your CI process, it would pass.)
