### ISSUE TITLE
Wrong tslint warnings in vue components

### ISSUE THREAD

**Issue by RSeidelsohn** [SublimeLinter/SublimeLinter-tslint#42]
Moving this from the Sublime Forum to here:

I use the **SublimeLinter-tslint** plugin in **Sublime Text 3.2.1, Build 3207** under **Windows 10** for linting the Typescript sections in my vue components. But in these I get a bunch of warnings that seem totally wrong to me, especially the first one that marks the `<script lang="ts">` opening tag itself - see the following screenshot regarding this issue:
![Screenshot of the warning message](https://forum.sublimetext.com/uploads/default/original/3X/c/e/cec152a3e91f0b7e85558ac1f078f6340f823671.png)

The view.settings for that file's syntax say `Packages/Vue Syntax Highlight/Vue Component.sublime-syntax`.

I have  installed the npm modules `typescript` and `tslint` globally under Windows with the `npm i -g ...` command. Besides that I use the following configuration for SublimeLinter:

    // SublimeLinter Settings - User
    {
        "linters": {
            // The name of the linter you installed
            "tslint": {
                // Disables the linter. The default here is 'not set'
                "disable": false,
                "chdir": "${project}",
            }
        },

        "paths": {
            "windows": ["C:/Program Files/nodejs/"]
        }
    }

**Comment by kaste** [comment]
Hi! That is typical an issue with the syntax. We currently select by default

https://github.com/SublimeLinter/SublimeLinter-tslint/blob/aa7028009d356ed63845e98440cf290ae4556889/linter.py#L20

It looks like the syntax you're using marks the `script` tag as already typescript. You can try to find a better selector and put it in your settings `'selector': 'what.you.found'`. E.g. put the cursor at the first char and hit `ctrl+alt+shift+P` (Menu > Tools > Developer > Show Scope`. Maybe there is also a better syntax package available on PackageControl. Ref: http://www.sublimelinter.com/en/stable/linter_settings.html#selector

Note: `chdir` is not a valid setting.

**Comment by RSeidelsohn** [comment]
Thank you so much. I will try this tomorrow and update my post here.

**Comment by kaste** [comment]
Sorry, but I don't get notifications if you edit your post. Okay, we're doing the linter and others do the syntaxes. 😁 We're out. 

But really, you probably live too much on the edge, afaik vue + ts is something not ready yet, and I think vue shifts to eslint + plugin for ts but it is not ready now. 

You can fix the syntax though. There are super-capable people in the Sublime forum. Do you have an issue against the Vue syntax repo?

**Comment by RSeidelsohn** [comment]
Thank you @kaste - and yes, you are probably right: ESLint will take over from TSLint, so it's probably not worth caring too much. But I'd say Vue+TS is not really on the edge, as vue-cli encourages using it and that's probably the tool most devs use for setting up a new Vue project, plus TS is still quite on the rise.
I am sorry that I do not understand the differences between linter and syntax in this case and possibly will reach out to syntax adjustments (although the sheer number of other tslint issues makes me want to stay away from it). Anyway, let's close this case as "won't do" for a good reason.
