### ISSUE TITLE
tslint no results

### ISSUE THREAD

**Issue by adevart** [SublimeLinter/SublimeLinter-tslint#44]
I have installed the tslint plugin in Sublime and configured it with the config settings but no tslint errors appear. tslint is working ok from the command-line (Mac Terminal) and shows the errors but it says tslint(ok) in the Sublime status bar and "no results" in the linter output panel.

I added the config file to the settings like so:

"linters":{"tslint":{"disabled":false, "args": ["--config tslintconfig.json"]}}

but it shows the same no matter if I use a correct path or incorrect path for the config file. If I set disabled to true, it removes the tslint(ok) from the status bar.

Turning on debugging doesn't show any errors. Is there a way to debug what command is being run? Is this the correct format for the args property?

**Comment by adevart** [comment]
I tried changing some setting with the config file and it started logging errors instead of tslint(ok). I changed --config to -c and that seemed to make a difference but I'm not sure why. It looks like it's logging tslint errors into the console output panel. The SublimeLinter panel says no lint results but the console panel is logging errors now and when I run the SublimeLinter > Lint This View command, it is logging the errors. I don't get any labels or markers in the UI though.

**Comment by kaste** [comment]
We continue on the SublimeLinter core issue you created, okay?

The args setting you posted here is not correct though. You either set it to a string which we then automatically split and in a sense quote for you. In case this splitting fails (more likely on Windows actually) you can also set it to an array but then you have to split on your own, here on the space between config and the filename.

**Comment by adevart** [comment]
Thanks for the reply, I tried it split in parts like this:

 ["--config", "tslintconfig.json"]

and it did the same (on Mac). The debug output shows the lint command and it looks ok. It's logging to the console though and not the Sublime Linter output panel.

The output to the console looks correct:

SublimeLinter: searching executable tslint
running...
tslint --format verbose filename.ts --config tslintconfig.json
tslint: output:
list of tslint issues
Linting source.ts took 0.5s.

When I open Output:SublimeLinter panel, it says filename.ts: No lint results.

**Comment by kaste** [comment]
You should not strip and mangle the debug output when posting, that doesn't make sense. That's not what we log afaik.

**Comment by adevart** [comment]
I read the other post in the core issue, it is logging some "no match" issues in the debug output:

SublimeLinter: #57 linter.py:1254     tslint: No match for line: '(no-unused-variable) GameController.ts[90, 17]: unused variable: 'display''

I guess it must be trying to parse the error line? Maybe I can modify the python to get it to match the output.

**Comment by adevart** [comment]
Would it be possible to add a custom regular expression matcher to the settings?

All I'd need it to do is grab the line number from the error like with this regex:

\[([0-9]*)[^\]]*\]

Then mark that line number with a gutter icon or change the background color of the line and have the error message in a hover box over the icon. I don't need it to do complex parsing of the error output.

**Comment by kaste** [comment]
Do you use a custom formatting here, maybe introduced by your config? Your output does not match any of the officially listed formats.

**Comment by adevart** [comment]
No custom output format, the json config file is just a list of rules to check. I'm using an old tslint version though - 2.5.1. Maybe I can upgrade the tslint version.

**Comment by adevart** [comment]
Ok, I got it working with a newer tslint version but the problem is they deprecated a few important rules in newer versions of tslint.

https://github.com/palantir/tslint/issues/4100

That's why my projects have an older tslint version. When I upgrade the tslint version, the Sublime Linter logs errors about a few rules being deprecated and when I remove the deprecated rules from the config file, it works ok.
