### ISSUE TITLE
Update readme to say tslint is depreciated

### ISSUE THREAD

**Issue by ghost** [SublimeLinter/SublimeLinter-tslint#45]

**Comment by kaste** [comment]
Honestly, you either make a PR, or make a good issue description, or...   

Technically *this* package here is not deprecated, as we just support the legacy.

**Comment by HopefulFire** [comment]
Sorry, I didn't mean to get on anyone's nerves. I just was a little irritated I set up tslint only to find that it is depreciated in the npm messages, had to uninstall, etc. It would be useful if there was at least some mention of tslint being depreciated in the readme / package manager for sublime text. Obviously that's up to you people though if you want something there or not.

**Comment by kaste** [comment]
Yeah, why not.  But of course we have lots of plugins for outdated/legacy linters.  A short PR is always welcome. 👍
